_BASE_: "Base-ConsistencyDet.yaml"
MODEL:
  WEIGHTS: "models/diffdet_coco_res101.pth"
  RESNETS:
    DEPTH: 101
    STRIDE_IN_1X1: False
  ConsistencyDet:
    NUM_PROPOSALS: 500
    NUM_CLASSES: 80
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST:  ("coco_2017_val",)
SOLVER:
  STEPS: (2000000, 5000000)
  MAX_ITER: 6000000
INPUT:
  CROP:
    ENABLED: True
  FORMAT: "RGB"
